MoeMemos.xcodeproj/project.pbxproj, MoeMemos/Helpers/SafariView.swift, MoeMemos/Views/Attachment.swift, MoeMemos/Views/MemoCard.swift, MoeMemos/Views/MemoInput.swift, MoeMemosWidgets/MoeMemosWidgets.intentdefinition
Read-only via SFSafariViewController for now.
Will support uploading non-image attachments in future (via UIDocumentPickerViewController).
=> feature: display non-image attachments

MoeMemos/Views/HeatmapStat.swift
=> fix: heatmap color on iPad dark theme

MoeMemos/Views/MemoInput.swift, MoeMemosShareExtension/ShareViewController.swift
=> feat: allow memos with only images

MoeMemos/Helpers/QuickLookRepresentable.swift, MoeMemos/Model/Memo.swift, MoeMemos/Model/User.swift, MoeMemos/Resources/Localization/en.lproj/Localizable.strings, MoeMemos/Resources/Localization/zh-Hans.lproj/Localizable.strings, MoeMemos/Resources/Localization/zh-Hant.lproj/Localizable.strings, MoeMemos/ViewModel/MemoInputViewModel.swift, MoeMemos/ViewModel/MemosViewModel.swift, MoeMemos/Views/MemoCard.swift, MoeMemos/Views/MemoInput.swift, MoeMemos/Views/MemosList.swift
Resolves #47 
The UI is (again) inspired by the Mastodon app [Ice Cubes](https://github.com/Dimillian/IceCubesApp), thanks 😄
=> feat: memo visibility option

MoeMemos.xcodeproj/project.pbxproj, MoeMemos.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, MoeMemos/API/Memos.swift, MoeMemos/API/MemosAPI.swift, MoeMemos/Helpers/Route.swift, MoeMemos/Model/Memo.swift, MoeMemos/Resources/Localization/en.lproj/Localizable.strings, MoeMemos/Resources/Localization/zh-Hans.lproj/Localizable.strings, MoeMemos/Resources/Localization/zh-Hant.lproj/Localizable.strings, MoeMemos/ViewModel/ExploreViewModel.swift, MoeMemos/Views/ArchivedMemoCard.swift, MoeMemos/Views/ArchivedMemosList.swift, MoeMemos/Views/Explore.swift, MoeMemos/Views/ExploreMemoCard.swift, MoeMemos/Views/MemoCard.swift, MoeMemos/Views/MemoCardContent.swift, MoeMemos/Views/Settings.swift, MoeMemos/Views/Sidebar.swift, MoeMemosShareExtension/ShareViewController.swift, MoeMemosWidgets/MemoryWidget.swift, MoeMemosWidgets/MemosGraphWidget.swift
=> feat: explore page

MoeMemos/Model/User.swift
=> fix: default memo visibility setting

MoeMemos/ViewModel/MemoInputViewModel.swift, MoeMemos/Views/MemoInput.swift
=> fix: prevent double tapping when saving memos

MoeMemos/Views/MemosList.swift
=> fix: support tag in the end of memo

MoeMemos.xcodeproj/project.pbxproj, MoeMemos/Helpers/TextView.swift, MoeMemos/Views/MemoInput.swift
=> insert tags to the correct position

MoeMemos/Helpers/TextView.swift
=> fix: freeze on iOS 15

MoeMemos/API/Memos.swift, MoeMemos/API/MemosAPI.swift, MoeMemos/ViewModel/MemosViewModel.swift, MoeMemos/Views/Sidebar.swift
=> feat: support deleting tags

MoeMemosShareExtension/ShareViewController.swift
=> fix: memory issue of share extension

MoeMemos/Helpers/Constants.swift, MoeMemos/Helpers/TextView.swift, MoeMemos/Views/MemoInput.swift
=> add checkbox icon when creating a memo

MoeMemos/API/Memos.swift
=> fix: add access token for local images

MoeMemos/Views/MemosList.swift
=> fix: select tags on sidebar on iPad

MoeMemosShareExtension/ShareViewController.swift
=> fix: screenshot sharing

MoeMemos/API/Memos.swift
=> fix: double percent-encoding

MoeMemos.xcodeproj/project.pbxproj, MoeMemosShareExtension/ShareViewController.swift
=> fix: update tags when create memos from share extension

MoeMemos/Model/Resource.swift, MoeMemos/Views/Attachment.swift, MoeMemos/Views/ResourceCard.swift
=> fix: compatibility with Memos 0.19

MoeMemos.xcodeproj/project.pbxproj, MoeMemos/Model/Resource.swift, MoeMemos/Views/Attachment.swift, MoeMemos/Views/ResourceCard.swift
=> fix: compatiblity with Memos 0.21

MoeMemos.xcodeproj/project.pbxproj, MoeMemos/Model/NestedTag.swift, MoeMemos/ViewModel/MemosViewModel.swift, MoeMemos/Views/Sidebar.swift, Packages/Models/Sources/Models/Tag.swift
- Support the nested tag syntax in Memos <= 0.21.
- Support using this feature in both Memos <= 0.21 and 0.22+.
- Resolves #90
=> feat: collapsible tags

Packages/Models/Sources/Models/Account.swift, Packages/Services/Sources/MemosV1Service/openapi.yaml
=> fix: type mismatch when parsing JSON

Packages/Services/Sources/MemosV1Service/Ext.swift, Packages/Services/Sources/MemosV1Service/MemosV1Service.swift, Packages/Services/Sources/MemosV1Service/openapi.yaml
=> feat: support Memos 0.23

MoeMemos/Helpers/Route.swift, MoeMemos/MoeMemosApp.swift, MoeMemos/ViewModel/MemosViewModel.swift
=> fix: crash when running on macOS
